{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "turn-discovery-service.serviceAccountName" . }}
  labels:
    {{- include "turn-discovery-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "turn-discovery-service.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "turn-discovery-service.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "turn-discovery-service.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "turn-discovery-service.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
